CREATE TABLE [DBO].[STOCK_SETTING](
	[STOCK_SETTING_ID] [INT] NOT NULL,
	[STOCK_SETTING_NAME] [VARCHAR](500) NOT NULL,
	[STOCK_SETTING_VALUE] [VARCHAR](100) NOT NULL,
	[STOCK_SETTING_UNIQUE_ID] [VARCHAR](100) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[STOCK_SETTING_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO