CREATE TABLE [dbo].[STOCK_DAILY_DATA](
	[STOCK_DAILY_DATA_ID] [int] IDENTITY(1,1) NOT NULL,
	[STOCK_ID] [int] NOT NULL,
	[STOCK_DATE] [datetime] NOT NULL,
	[HIGH_PRICE] [decimal](10, 2) NULL,
	[LOW_PRICE] [decimal](10, 2) NULL,
	[OPEN_PRICE] [decimal](10, 2) NULL,
	[CLOSE_PRICE] [decimal](10, 2) NULL,
	[VOLUME] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[STOCK_DAILY_DATA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[STOCK_DAILY_DATA] ADD FOREIGN KEY([STOCK_ID])
REFERENCES [dbo].[STOCK_NAME] ([STOCK_ID])
GO
